# Generated by Django 5.0.7 on 2024-07-28 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Provide a detailed description of the expense.', null=True, verbose_name='Description')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Equal'), (2, 'Exact'), (3, 'Percentage')], verbose_name='Expense Type')),
                ('cost', models.IntegerField(verbose_name='Total cost of expense')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_administered', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.IntegerField(verbose_name='Contribution of Participant')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expense.expense')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_expense', to=settings.AUTH_USER_MODEL, verbose_name='ParticipantUser')),
            ],
            options={
                'unique_together': {('expense', 'participant')},
            },
        ),
    ]
