# Generated by Django 5.0.7 on 2024-07-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseparticipant',
            name='contribution',
            field=models.FloatField(default=0, verbose_name='Contribution of Participant'),
        ),
    ]
